import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../constants/app_colors.dart';
import '../constants/app_typography.dart';

class AppTheme {
  AppTheme._();

    static ThemeData get dark => ThemeData(
        useMaterial3: true,
            brightness: Brightness.dark,
                scaffoldBackgroundColor: AppColors.black,
                    primaryColor: AppColors.purple,
                        colorScheme: const ColorScheme.dark(
                              primary: AppColors.purple,
                                    secondary: AppColors.gold,
                                          surface: AppColors.surface,
                                                error: AppColors.hp,
                                                      onPrimary: AppColors.textPrimary,
                                                            onSecondary: AppColors.black,
                                                                  onSurface: AppColors.textPrimary,
                                                                      ),

                                                                          // AppBar
                                                                              appBarTheme: const AppBarTheme(
                                                                                    backgroundColor: AppColors.black,
                                                                                          elevation: 0,
                                                                                                centerTitle: true,
                                                                                                      titleTextStyle: AppTypography.titleLarge,
                                                                                                            systemOverlayStyle: SystemUiOverlayStyle(
                                                                                                                    statusBarColor: Colors.transparent,
                                                                                                                            statusBarIconBrightness: Brightness.light,
                                                                                                                                  ),
                                                                                                                                      ),

                                                                                                                                          // Cards
                                                                                                                                              cardTheme: CardTheme(
                                                                                                                                                    color: AppColors.surface,
                                                                                                                                                          elevation: 0,
                                                                                                                                                                shape: RoundedRectangleBorder(
                                                                                                                                                                        borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                side: const BorderSide(
                                                                                                                                                                                          color: AppColors.border,
                                                                                                                                                                                                    width: 1,
                                                                                                                                                                                                            ),
                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                          // Botões
                                                                                                                                                                                                                              elevatedButtonTheme: ElevatedButtonThemeData(
                                                                                                                                                                                                                                    style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                            backgroundColor: AppColors.purple,
                                                                                                                                                                                                                                                    foregroundColor: AppColors.textPrimary,
                                                                                                                                                                                                                                                            elevation: 0,
                                                                                                                                                                                                                                                                    padding: const EdgeInsets.symmetric(
                                                                                                                                                                                                                                                                              horizontal: 24,
                                                                                                                                                                                                                                                                                        vertical: 14,
                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                        shape: RoundedRectangleBorder(
                                                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(8),
                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                  textStyle: AppTypography.bodyLarge,
                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                // Text buttons
                                                                                                                                                                                                                                                                                                                                                    textButtonTheme: TextButtonThemeData(
                                                                                                                                                                                                                                                                                                                                                          style: TextButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                  foregroundColor: AppColors.purple,
                                                                                                                                                                                                                                                                                                                                                                          textStyle: AppTypography.bodyMedium,
                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                        // Inputs
                                                                                                                                                                                                                                                                                                                                                                                            inputDecorationTheme: InputDecorationTheme(
                                                                                                                                                                                                                                                                                                                                                                                                  filled: true,
                                                                                                                                                                                                                                                                                                                                                                                                        fillColor: AppColors.surfaceAlt,
                                                                                                                                                                                                                                                                                                                                                                                                              border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.circular(8),
                                                                                                                                                                                                                                                                                                                                                                                                                              borderSide: const BorderSide(color: AppColors.border),
                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                          enabledBorder: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: BorderRadius.circular(8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderSide: const BorderSide(color: AppColors.border),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      focusedBorder: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: BorderRadius.circular(8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderSide: const BorderSide(color: AppColors.purple, width: 1.5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelStyle: AppTypography.bodyMedium,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hintStyle: AppTypography.bodySmall,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Divisores
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dividerTheme: const DividerThemeData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: AppColors.border,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                thickness: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Bottom Navigation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bottomNavigationBarTheme: const BottomNavigationBarThemeData(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: AppColors.surface,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        selectedItemColor: AppColors.purple,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              unselectedItemColor: AppColors.textMuted,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: BottomNavigationBarType.fixed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          elevation: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Texto global
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textTheme: const TextTheme(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            displayLarge: AppTypography.displayLarge,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  displayMedium: AppTypography.displayMedium,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        titleLarge: AppTypography.titleLarge,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              bodyLarge: AppTypography.bodyLarge,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bodyMedium: AppTypography.bodyMedium,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bodySmall: AppTypography.bodySmall,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }